[package]
name = "mt_logger"
version = "0.3.0"
authors = ["CJ McAllister <cjm571@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "^0.4"
once_cell = "^1.7"